apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sheetmusic.fullname" . }}-secret
data:
  SQL_PASSWORD: {{ tpl .Values.sheetmusic.sql.password . | b64enc | quote }}
  SMTP_PASSWORD: {{ tpl .Values.sheetmusic.smtp.password . | b64enc | quote }}
